version: "3.9"

services:
  waha:
    image: devlikeapro/waha:latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      WHATSAPP_HOOK_URL: ${WHATSAPP_HOOK_URL}
      WHATSAPP_DEFAULT_ENGINE: ${WHATSAPP_DEFAULT_ENGINE}
      WHATSAPP_HOOK_EVENTS: ${WHATSAPP_HOOK_EVENTS}
      WAHA_NO_API_KEY: ${WAHA_NO_API_KEY}
      WAHA_API_KEY: ${WAHA_API_KEY}
      WAHA_DASHBOARD_NO_PASSWORD: ${WAHA_DASHBOARD_NO_PASSWORD}
      WAHA_DASHBOARD_USERNAME: ${WAHA_DASHBOARD_USERNAME}
      WAHA_DASHBOARD_PASSWORD: ${WAHA_DASHBOARD_PASSWORD}
      WHATSAPP_SWAGGER_NO_PASSWORD: ${WHATSAPP_SWAGGER_NO_PASSWORD}
      WAHA_APPS_ENABLED: ${WAHA_APPS_ENABLED}
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media
    ports:
      - "127.0.0.1:3000:3000"

  n8n:
    image: n8nio/n8n:latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      N8N_HOST: ${N8N_HOST}
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      N8N_LOG_LEVEL: ${N8N_LOG_LEVEL}
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: ${N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: ${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      QUEUE_BULL_REDIS_HOST: ${QUEUE_BULL_REDIS_HOST}
      QUEUE_BULL_REDIS_PORT: ${QUEUE_BULL_REDIS_PORT}
      QUEUE_BULL_REDIS_PASSWORD: ${QUEUE_BULL_REDIS_PASSWORD}
      QUEUE_BULL_REDIS_TLS: ${QUEUE_BULL_REDIS_TLS}
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "127.0.0.1:5678:5678"

volumes:
  waha_sessions:
  waha_media:
  n8n_data:
